version: "3.9"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: .
    restart: always
    command: bash -c "bundle exec rake db:create db:migrate && bundle exec puma -p 9292 -b 'tcp://0.0.0.0'"
    volumes:
      - .:/echo
    ports:
      - "9292:9292"
    depends_on:
      - db