development:
  :adapter: postgres
  :encoding: unicode
  :pool: 5
  :database: sinatra_starter_dev
  :host: localhost

test:
  :adapter: postgres
  :encoding: unicode
  :database: sinatra_starter_test